name: ci it.bz.opendatahub.analytics

on: 
  push:
   # commented out because a lot of branches exist in this repo
   # branches: [development, master]
    paths:
      - "!README.md"
      
  pull_request:
   # commented out because a lot of branches exist in this repo
   # branches: [development, master]
    paths:
      - "!README.md"


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: clone into repo
        uses: actions/checkout@v2

      - name: Test
        run: |
          cd src/main/webapp
          test -f index.html
          test -f dotenv.js
